on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:
name: CI Build Flatpak
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-49
      options: --privileged
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6.6
        with:
          bundle: atkAudio
          manifest-path: com.obsproject.Studio.Plugin.atkAudio.yaml
          cache-key: flatpak-builder-${{ github.sha }}

  release:
    runs-on: ubuntu-latest
    needs: [flatpak]
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v5
      - name: Rename release file
        run: |
          mv atkAudio atkAudioForOBS-0.31.15.flatpak
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          name: atkAudio Plugin for OBS Flatpak 0.31.15
          preserve_order: true
          files: |
            atkAudioForOBS-0.31.15.flatpak